# @format

name: bagiin
description: "Bagikan momenmu di Bagiin"

publish_to: "none"

version: 0.1.0+1 #-- Alpha Version --#

environment:
  sdk: ^3.5.3

#---------------------- Packages ----------------------#
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hexcolor: ^3.0.1
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.5
  feather_icons: ^1.2.0
  carousel_slider: ^5.0.0
  email_validator: ^3.0.0
  image_picker: ^1.1.2
  image_cropper: ^7.1.0
  permission_handler: ^11.3.1
  lottie: ^3.1.2
#-------------------- Packages Ends -------------------#

#---------------------- Dev Packages ----------------------#
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
#-------------------- Dev Packages Ends -------------------#

flutter:
  uses-material-design: true

  #---------------------- Local Assets ----------------------#
  assets:
    - assets/
    - assets/img/
    - assets/img/illustration/
    - assets/img/logo/
  #-------------------- Local Assets Ends -------------------#

  #---------------------- Fonts ----------------------#
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lato-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/Lato-BlackItalic.ttf
          weight: 900
          style: italic
  #-------------------- Fonts Ends -------------------#

#------------------- Flutter Native Splash -------------------#
flutter_native_splash:
  color: "#ffffff"
  color_dark: "#363636"
  image: "assets/img/logo/logo-bagiin-splash.png"
  image_dark: "assets/img/logo/logo-bagiin-splash.png"
  android_12:
    image: "assets/img/logo/logo-bagiin-splash.png"
    color: "#ffffff"
    image_dark: "assets/img/logo/logo-bagiin-splash.png"
    color_dark: "#363636"
  android: true
  ios: true
#------------------- Flutter Native Splash Ends -------------------#

#------------------- Flutter Launcher Icons -------------------#
flutter_launcher_icons:
  android: "ic_launcher"
  ios: "AppIcon"
  image_path: "assets/img/logo/play_store_512.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/img/logo/play_store_512.png"
  remove_alpha_ios: true
#----------------- Flutter Launcher Icons Ends -----------------#
